[profile.default]
#solc = "0.8.30"
auto_detect_solc = true
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
evm_version = "prague"

remappings = [
    "@gnosis.pm=node_modules/@gnosis.pm",
    "@openzeppelin=node_modules/@openzeppelin",
    "@account-abstraction=node_modules/@account-abstraction",
    "canonical-weth=node_modules/canonical-weth",
]